#!/usr/bin/env python3
"""
Telegram Bot Engine for Universal AI Brain.
Supports long-polling and webhook dispatching for omniscient mobile knowledge access.
"""

import os
import sys
import json
import time
import urllib.request
import urllib.parse
import sqlite3
from typing import Dict, Any, Optional, List
from collections import deque

TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "8615414934:AAEGBkrHPQaEestCzHMDSEB6iKyYYTOK7LY").replace(" ", "")
DB_PATH = os.getenv("BRAIN_DB_PATH", os.path.join(os.path.dirname(os.path.abspath(__file__)), "brain.db"))


def get_db():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL;")
    conn.execute("PRAGMA foreign_keys=ON;")
    return conn


def send_telegram_message(chat_id: int, text: str, parse_mode: str = "HTML", reply_markup: Optional[Dict[str, Any]] = None) -> bool:
    """Send a message to Telegram via Bot API."""
    if not TELEGRAM_BOT_TOKEN:
        return False
    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": text,
        "parse_mode": parse_mode,
        "disable_web_page_preview": True
    }
    if reply_markup:
        payload["reply_markup"] = reply_markup

    try:
        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"}
        )
        with urllib.request.urlopen(req, timeout=10) as resp:
            return resp.status == 200
    except Exception as e:
        print(f"[Telegram Bot Error] Failed to send message: {e}", file=sys.stderr)
        return False


def get_main_keyboard() -> Dict[str, Any]:
    """Returns the quick-access keyboard for Telegram mobile clients."""
    return {
        "keyboard": [
            [{"text": "📋 Menu Comandi"}, {"text": "📊 Statistiche Cervello"}],
            [{"text": "💻 Terminale Log"}, {"text": "🌳 Albero Gerarchico"}],
            [{"text": "📥 Posta JSON AI"}, {"text": "🔍 Ricerca Progetti"}]
        ],
        "resize_keyboard": True,
        "persistent": True
    }


def sanitize_and_translate_text(text: str) -> str:
    """Translates common Chinese/Wenyan terms to Italian/English to guarantee pure FTS5 search."""
    if not text:
        return text
    replacements = {
        "層級譜系樹": "Albero Gerarchico (Hierarchical Tree)",
        "譜系樹": "Albero Gerarchico",
        "樹狀結構技術評析": "Valutazione Tecnica Strutture ad Albero",
        "知識圖譜": "Knowledge Graph",
        "神經符號": "Neuro-Simbolico",
        "胼胝體": "Corpo Calloso",
        "雙半球": "Bi-Emisferico",
        "半球": "Emisfero",
        "左半球": "Emisfero Sinistro",
        "右半球": "Emisfero Destro",
        "突觸": "Sinapsi",
        "節點": "Nodo",
        "路徑": "Percorso",
        "檢索": "Ricerca FTS",
        "認知": "Cognitivo",
        "架構": "Architettura",
        "意圖": "Intento Utente",
        "推演": "Deduzione AI",
        "對話": "Episodio Conversazionale",
        "通透無礙，極佳之策": "Strategia ottimale approvata",
        "冠絕群策者": "Migliore Soluzione Eletta",
        "已全面構建完成": "Completamente rilasciato e verificato"
    }
    cleaned = text
    for k, v in replacements.items():
        cleaned = cleaned.replace(k, v)
    return cleaned


def parse_and_ingest_json_payload(raw_text: str, user_name: str) -> Optional[str]:
    """
    Detects, parses, and ingests JSON payloads generated by LLMs (Claude, ChatGPT, Gemini).
    Supports markdown ```json blocks or raw JSON dictionaries/lists.
    """
    cleaned = raw_text.strip()
    if cleaned.startswith("/post") or cleaned.startswith("/ingest"):
        cleaned = cleaned.replace("/post", "", 1).replace("/ingest", "", 1).strip()

    # Extract JSON inside markdown code blocks if present
    if "```" in cleaned:
        parts = cleaned.split("```")
        for part in parts:
            p_strip = part.strip()
            if p_strip.startswith("json"):
                p_strip = p_strip[4:].strip()
            if (p_strip.startswith("{") and p_strip.endswith("}")) or (p_strip.startswith("[") and p_strip.endswith("]")):
                cleaned = p_strip
                break

    # Check if text looks like JSON
    if not ((cleaned.startswith("{") and cleaned.endswith("}")) or (cleaned.startswith("[") and cleaned.endswith("]"))):
        return None

    try:
        data = json.loads(cleaned)
    except Exception:
        return None

    # Normalize structure to nodes and edges
    nodes_list: List[Dict[str, Any]] = []
    edges_list: List[Dict[str, Any]] = []

    if isinstance(data, dict):
        if "nodes" in data and isinstance(data["nodes"], list):
            nodes_list = data["nodes"]
            edges_list = data.get("edges", []) or data.get("links", [])
        elif "id" in data and "label" in data:
            nodes_list = [data]
    elif isinstance(data, list):
        nodes_list = [item for item in data if isinstance(item, dict) and "id" in item]

    if not nodes_list:
        return None

    # Ingest into SQLite database
    now_iso = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    nodes_upserted = 0
    edges_upserted = 0
    inserted_nodes_summary = []

    with get_db() as conn:
        cross_links_to_add = []
        for n in nodes_list:
            slug = sanitize_and_translate_text(str(n.get("id", ""))).strip().lower().replace(" ", "-")
            if not slug:
                continue
            label = sanitize_and_translate_text(str(n.get("label", slug)).strip())
            hemisphere = str(n.get("hemisphere", "LEFT")).strip().upper()
            if hemisphere not in ("LEFT", "RIGHT"):
                hemisphere = "LEFT"
            primary_label = str(n.get("primary_label", n.get("category", "ARCHITECTURE"))).strip().upper()
            category = str(n.get("category", primary_label)).strip()
            
            tags = n.get("tags", [])
            if isinstance(tags, list):
                tags_str = json.dumps([sanitize_and_translate_text(str(t)).strip().lower() for t in tags if str(t).strip()])
            else:
                tags_str = json.dumps(["json-import"])

            summary = sanitize_and_translate_text(str(n.get("summary", label)).strip())
            details = n.get("details", {})
            if isinstance(details, dict):
                details["ingested_via"] = "telegram_json_post"
                details["user"] = user_name
                details_str = json.dumps(details)
            else:
                details_str = json.dumps({"raw_details": str(details)})

            confidence = str(n.get("confidence", "EXTRACTED")).strip().upper()
            if confidence not in ("EXTRACTED", "INFERRED", "AMBIGUOUS"):
                confidence = "EXTRACTED"

            existing = conn.execute("SELECT created_at FROM nodes WHERE id = ?", (slug,)).fetchone()
            created_at = existing["created_at"] if existing else now_iso

            conn.execute("""
                INSERT OR REPLACE INTO nodes
                (id, label, hemisphere, primary_label, category, tags, summary, details, confidence, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (slug, label, hemisphere, primary_label, category, tags_str, summary, details_str, confidence, created_at, now_iso))
            nodes_upserted += 1

            hemi_icon = "⚡" if hemisphere == "LEFT" else "🌸"
            inserted_nodes_summary.append(f"{hemi_icon} <b>{label}</b> (<code>{slug}</code>) · <i>{primary_label}</i>")

            # Collect cross links
            for tgt in n.get("cross_links", []):
                tgt_slug = sanitize_and_translate_text(str(tgt)).strip().lower()
                if tgt_slug and tgt_slug != slug:
                    cross_links_to_add.append((slug, tgt_slug))

        # Insert cross links
        for s, t in cross_links_to_add:
            if conn.execute("SELECT 1 FROM nodes WHERE id = ?", (t,)).fetchone():
                conn.execute("""
                    INSERT OR REPLACE INTO edges (source, target, relation, confidence, reasoning, created_at)
                    VALUES (?, ?, 'CORPUS_CALLOSUM_LINK', 'EXTRACTED', 'Cross-hemisphere bridge', ?)
                """, (s, t, now_iso))
                edges_upserted += 1

        # Insert explicit edges
        for e in edges_list:
            if not isinstance(e, dict):
                continue
            src = str(e.get("source", "")).strip().lower()
            tgt = str(e.get("target", "")).strip().lower()
            rel = str(e.get("relation", "CONNECTS")).strip().upper().replace(" ", "_")
            conf = str(e.get("confidence", "EXTRACTED")).strip().upper()
            reason = e.get("reasoning", None)

            if conn.execute("SELECT 1 FROM nodes WHERE id = ?", (src,)).fetchone() and \
               conn.execute("SELECT 1 FROM nodes WHERE id = ?", (tgt,)).fetchone():
                conn.execute("""
                    INSERT OR REPLACE INTO edges (source, target, relation, confidence, reasoning, created_at)
                    VALUES (?, ?, ?, ?, ?, ?)
                """, (src, tgt, rel, conf, reason, now_iso))
                edges_upserted += 1

        conn.commit()
        total_nodes = conn.execute("SELECT COUNT(*) AS c FROM nodes").fetchone()["c"]
        total_edges = conn.execute("SELECT COUNT(*) AS c FROM edges").fetchone()["c"]

    nodes_formatted = "\n".join(f"• {item}" for item in inserted_nodes_summary[:10])
    if len(inserted_nodes_summary) > 10:
        nodes_formatted += f"\n<i>...e altri {len(inserted_nodes_summary)-10} nodi</i>"

    return (
        f"📥 <b>PAYLOAD JSON AI INGESTITO CON SUCCESSO!</b>\n"
        f"────────────────────────\n"
        f"✨ <b>Nodi Inseriti/Aggiornati:</b> {nodes_upserted}\n"
        f"🔗 <b>Sinapsi Collegate:</b> {edges_upserted}\n\n"
        f"<b>Dettaglio Nodi:</b>\n"
        f"{nodes_formatted}\n"
        f"────────────────────────\n"
        f"🧠 <b>Totale Cervello:</b> {total_nodes} nodi · {total_edges} sinapsi\n"
        f"🌐 <i>Visualizza:</i> https://universal-ai-brain.onrender.com"
    )


def process_telegram_message(chat_id: int, user_name: str, text: str) -> str:
    """Process incoming command, JSON payload, or natural language thought."""
    cmd = text.strip()

    # 1. Check if the message is a JSON payload from AI or /post /ingest
    json_response = parse_and_ingest_json_payload(cmd, user_name)
    if json_response:
        return json_response

    # 2. /start, /help, /menu
    if cmd in ("/start", "/help", "/menu", "help", "menu", "📋 Menu Comandi"):
        return (
            f"🧠 <b>UNIVERSAL AI BRAIN - MENU COMANDI</b>\n"
            f"<i>Connesso all'intelligenza di Pierfrancesco</i>\n"
            f"────────────────────────\n"
            f"<b>🔍 Navigazione & Ricerca:</b>\n"
            f"• <code>/search &lt;query&gt;</code> - Ricerca BM25 istantanea\n"
            f"• <code>/tree</code> - Albero gerarchico di tutte le categorie\n"
            f"• <code>/stats</code> - Metriche globali (nodi, sinapsi, ponti)\n"
            f"• <code>/path &lt;id1&gt; &lt;id2&gt;</code> - Cammino minimo tra concetti\n"
            f"• <code>/terminal</code> - Console e log delle ultime attività/notifiche\n\n"
            f"<b>📥 Inserimento & Ingestione:</b>\n"
            f"• <b>Incolla JSON di ChatGPT/Claude</b> - Riconoscimento e salvataggio automatico!\n"
            f"• <code>/post &lt;JSON&gt;</code> - Inserimento esplicito blocco JSON\n"
            f"• <code>/add &lt;titolo&gt; | &lt;sintesi&gt;</code> - Inserimento rapido nota/idea\n"
            f"• <b>Messaggio libero</b> - Salva all'istante una nuova memoria\n\n"
            f"<b>🌐 Web Dashboard:</b>\n"
            f"https://universal-ai-brain.onrender.com"
        )

    # 3. /terminal or /logs
    if cmd in ("/terminal", "/logs", "terminal", "logs", "💻 Terminale Log"):
        with get_db() as conn:
            recent_nodes = conn.execute("""
                SELECT id, label, hemisphere, primary_label, confidence, updated_at, details
                FROM nodes
                ORDER BY datetime(updated_at) DESC
                LIMIT 8
            """).fetchall()

            recent_edges = conn.execute("""
                SELECT source, target, relation, confidence, created_at
                FROM edges
                ORDER BY datetime(created_at) DESC
                LIMIT 4
            """).fetchall()

            tot_nodes = conn.execute("SELECT COUNT(*) AS c FROM nodes").fetchone()["c"]
            tot_edges = conn.execute("SELECT COUNT(*) AS c FROM edges").fetchone()["c"]

            log_entries = []
            for n in recent_nodes:
                ts = n["updated_at"].replace("T", " ")[:19] if n["updated_at"] else "RECENT"
                hemi_ico = "⚡" if n["hemisphere"] == "LEFT" else "🌸"
                log_entries.append(
                    f"<code>[{ts}]</code> 🟢 <b>[NODE_UPSERT]</b>\n"
                    f"  {hemi_ico} <b>{n['label']}</b> (<code>{n['id']}</code>)\n"
                    f"  📂 <i>{n['primary_label']}</i> · <code>{n['confidence']}</code>"
                )

            edge_entries = []
            for e in recent_edges:
                ts = e["created_at"].replace("T", " ")[:19] if e["created_at"] else "RECENT"
                edge_entries.append(
                    f"<code>[{ts}]</code> 🔗 <b>[SYNAPSE]</b> <code>{e['source']}</code> --[{e['relation']}]--> <code>{e['target']}</code>"
                )

            logs_formatted = "\n\n".join(log_entries)
            edges_formatted = "\n".join(edge_entries)

            return (
                f"💻 <b>COGNITIVE TERMINAL &amp; LIVE ACTIVITY LOGS</b>\n"
                f"<code>brain@ai-backend:~/journal/activity.log</code>\n"
                f"────────────────────────\n"
                f"<b>📡 Ultimi Nodi Inseriti / Aggiornati:</b>\n\n"
                f"{logs_formatted}\n\n"
                f"<b>🔗 Ultime Sinapsi Generate:</b>\n"
                f"{edges_formatted}\n"
                f"────────────────────────\n"
                f"📊 <b>Stato Kernel:</b> ONLINE (SQLite WAL) · {tot_nodes} nodi · {tot_edges} sinapsi\n"
                f"🌐 <i>Live Console Web:</i> https://universal-ai-brain.onrender.com"
            )

    # 3. /stats
    if cmd in ("/stats", "📊 Statistiche Cervello"):
        with get_db() as conn:
            tot = conn.execute("SELECT COUNT(*) AS c FROM nodes").fetchone()["c"]
            left = conn.execute("SELECT COUNT(*) AS c FROM nodes WHERE hemisphere = 'LEFT'").fetchone()["c"]
            right = conn.execute("SELECT COUNT(*) AS c FROM nodes WHERE hemisphere = 'RIGHT'").fetchone()["c"]
            edges = conn.execute("SELECT COUNT(*) AS c FROM edges").fetchone()["c"]
            callosum = conn.execute("SELECT COUNT(*) AS c FROM edges WHERE relation = 'CORPUS_CALLOSUM_LINK'").fetchone()["c"]

            return (
                f"📊 <b>STATO DEL CERVELLO COGNITIVO</b>\n"
                f"────────────────────────\n"
                f"🧠 <b>Nodi Totali:</b> {tot}\n"
                f"⚡ <b>Emisfero Sinistro (Logica/Tech):</b> {left}\n"
                f"🌸 <b>Emisfero Destro (Arte/Emozioni):</b> {right}\n"
                f"🔗 <b>Sinapsi Totali:</b> {edges}\n"
                f"🌌 <b>Ponti Corpo Calloso:</b> {callosum}\n"
                f"────────────────────────\n"
                f"🌐 <i>Web Dashboard:</i> https://universal-ai-brain.onrender.com"
            )

    # 4. Instructions for JSON posting
    if cmd in ("📥 Posta JSON AI", "/post", "/ingest"):
        return (
            f"📥 <b>COME POSTARE I JSON DELLE AI</b>\n"
            f"────────────────────────\n"
            f"Puoi incollare direttamente in questa chat qualsiasi blocco JSON generato da <b>Claude, ChatGPT o Gemini</b>.\n\n"
            f"<b>Esempio di blocco supportato:</b>\n"
            f"<code>```json\n"
            f"{{\n"
            f"  \"nodes\": [\n"
            f"    {{\n"
            f"      \"id\": \"nuovo-concetto\",\n"
            f"      \"label\": \"Nuovo Concetto\",\n"
            f"      \"hemisphere\": \"LEFT\",\n"
            f"      \"primary_label\": \"ARCHITECTURE\",\n"
            f"      \"tags\": [\"ai\", \"tech\"],\n"
            f"      \"summary\": \"Descrizione sintetica\",\n"
            f"      \"confidence\": \"EXTRACTED\"\n"
            f"    }}\n"
            f"  ],\n"
            f"  \"edges\": []\n"
            f"}}\n"
            f"```</code>\n\n"
            f"<i>Incolla il JSON qui sotto e il bot lo elaborerà all'istante!</i>"
        )

    # 5. /search <query>
    if cmd.startswith("/search") or cmd.startswith("🔍 Ricerca"):
        query = cmd.replace("/search", "").replace("🔍 Ricerca Progetti", "").replace("🔍 Ricerca", "").strip()
        if not query:
            return "⚠️ <i>Uso:</i> <code>/search &lt;termine o tecnologia&gt;</code>\nEsempio: <code>/search flutter</code>"

        with get_db() as conn:
            terms = [f'"{t.replace(chr(34), "")}"*' for t in query.split() if t.strip()]
            match_query = " ".join(terms) if terms else query
            try:
                cursor = conn.execute("""
                    SELECT id FROM nodes_fts
                    WHERE nodes_fts MATCH ?
                    ORDER BY rank
                    LIMIT 5
                """, (match_query,))
                matched_ids = [r["id"] for r in cursor.fetchall()]
            except Exception:
                search_like = f"%{query.lower()}%"
                cursor = conn.execute("""
                    SELECT id FROM nodes
                    WHERE lower(id) LIKE ? OR lower(label) LIKE ? OR lower(summary) LIKE ? OR lower(tags) LIKE ?
                    LIMIT 5
                """, (search_like, search_like, search_like, search_like))
                matched_ids = [r["id"] for r in cursor.fetchall()]

            if not matched_ids:
                return f"🔍 Nessun nodo trovato per <b>'{query}'</b>."

            placeholders = ",".join("?" for _ in matched_ids)
            nodes = conn.execute(f"SELECT * FROM nodes WHERE id IN ({placeholders})", matched_ids).fetchall()

            res_lines = [f"🔍 <b>Risultati per '{query}':</b>\n"]
            for n in nodes:
                hemi_icon = "⚡" if n["hemisphere"] == "LEFT" else "🌸"
                tags = json.loads(n["tags"]) if n["tags"] else []
                tags_str = " ".join(f"#{t}" for t in tags[:3])
                res_lines.append(
                    f"{hemi_icon} <b>{n['label']}</b> (<code>{n['id']}</code>)\n"
                    f"📂 <i>{n['primary_label']}</i> | {tags_str}\n"
                    f"📝 {n['summary']}\n"
                )
            return "\n".join(res_lines)

    # 6. /tree
    if cmd in ("/tree", "🌳 Albero Gerarchico"):
        with get_db() as conn:
            left_tax = conn.execute("SELECT primary_label, COUNT(*) AS c FROM nodes WHERE hemisphere = 'LEFT' GROUP BY primary_label ORDER BY c DESC").fetchall()
            right_tax = conn.execute("SELECT primary_label, COUNT(*) AS c FROM nodes WHERE hemisphere = 'RIGHT' GROUP BY primary_label ORDER BY c DESC").fetchall()

            lines = ["🌳 <b>ALBERO GERARCHICO DI CONOSCENZA</b>\n"]
            lines.append("⚡ <b>Emisfero Sinistro (Logica & Tech):</b>")
            for t in left_tax:
                lines.append(f"  📂 <code>{t['primary_label']}</code>: {t['c']} nodi")
            lines.append("\n🌸 <b>Emisfero Destro (Design, Valori, Emozioni):</b>")
            for t in right_tax:
                lines.append(f"  📂 <code>{t['primary_label']}</code>: {t['c']} nodi")
            lines.append("\n<i>Consulta l'albero completo su:</i>\nhttps://universal-ai-brain.onrender.com/brain.md?view=tree")
            return "\n".join(lines)

    # 7. /path <from> <to>
    if cmd.startswith("/path") or cmd.startswith("⚡ Corpo Calloso"):
        args = cmd.replace("/path", "").replace("⚡ Corpo Calloso", "").strip().split()
        if len(args) < 2:
            return "⚠️ <i>Uso:</i> <code>/path &lt;id_sorgente&gt; &lt;id_destinazione&gt;</code>\nEsempio: <code>/path proj-caretrack lesson-stoic-resilience</code>"
        
        src, tgt = args[0].lower(), args[1].lower()
        with get_db() as conn:
            nodes_rows = conn.execute("SELECT id, label, hemisphere FROM nodes").fetchall()
            nodes_map = {r["id"]: dict(r) for r in nodes_rows}
            if src not in nodes_map or tgt not in nodes_map:
                return f"❌ Uno o entrambi i nodi non esistono: <code>{src}</code>, <code>{tgt}</code>"

            edges_rows = conn.execute("SELECT source, target, relation FROM edges").fetchall()
            adj: Dict[str, List[Dict[str, str]]] = {}
            for r in edges_rows:
                adj.setdefault(r["source"], []).append({"neighbor": r["target"], "rel": r["relation"]})
                adj.setdefault(r["target"], []).append({"neighbor": r["source"], "rel": r["relation"]})

            queue = deque([[src]])
            visited = {src}
            found_path = None
            while queue:
                p = queue.popleft()
                c = p[-1]
                if c == tgt:
                    found_path = p
                    break
                for nbr_info in adj.get(c, []):
                    nbr = nbr_info["neighbor"]
                    if nbr not in visited:
                        visited.add(nbr)
                        queue.append(p + [nbr])

            if not found_path:
                return f"❌ Nessun percorso sinaptico trovato tra <code>{src}</code> e <code>{tgt}</code>."

            chain = " ➜\n".join(f"• <b>{nodes_map[nid]['label']}</b> (<code>{nid}</code>)" for nid in found_path)
            return (
                f"⚡ <b>CAMMINO SINAPTICO TROVATO (Distanza: {len(found_path)-1})</b>\n"
                f"────────────────────────\n"
                f"{chain}\n"
                f"────────────────────────"
            )

    # 8. /add or free thought insertion
    note_content = cmd.replace("/add", "").strip()
    if not note_content:
        return "⚠️ Invia un testo per registrarlo come nuova memoria nel cervello."

    parts = note_content.split("|")
    title = parts[0].strip()
    summary = parts[1].strip() if len(parts) > 1 else title

    slug = "tg-" + "".join(c if c.isalnum() else "-" for c in title.lower())[:30].strip("-")
    now_iso = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    with get_db() as conn:
        conn.execute("""
            INSERT OR REPLACE INTO nodes
            (id, label, hemisphere, primary_label, category, tags, summary, details, confidence, created_at, updated_at)
            VALUES (?, ?, 'RIGHT', 'CREATIVE_IDEA', 'Telegram Note', ?, ?, ?, 'EXTRACTED', ?, ?)
        """, (
            slug, title,
            json.dumps(["telegram", "mobile-note", "quick-thought"]),
            summary,
            json.dumps({"source": "telegram-bot", "user": user_name}),
            now_iso, now_iso
        ))
        
        # Link to person-pierfrancesco
        if conn.execute("SELECT 1 FROM nodes WHERE id = 'person-pierfrancesco'").fetchone():
            conn.execute("""
                INSERT OR REPLACE INTO edges (source, target, relation, confidence, reasoning, created_at)
                VALUES ('person-pierfrancesco', ?, 'CAPTURED_VIA_TELEGRAM', 'EXTRACTED', 'Mobile thought capture', ?)
            """, (slug, now_iso))

        conn.commit()
        tot = conn.execute("SELECT COUNT(*) AS c FROM nodes").fetchone()["c"]

    return (
        f"✅ <b>MEMORIA SALVATA CON SUCCESSO!</b>\n"
        f"────────────────────────\n"
        f"📌 <b>Titolo:</b> {title}\n"
        f"🔑 <b>ID:</b> <code>{slug}</code>\n"
        f"📂 <b>Categoria:</b> CREATIVE_IDEA (Right Hemisphere)\n"
        f"📝 <b>Sintesi:</b> {summary}\n"
        f"🧠 <b>Nodi totali nel Cervello:</b> {tot}\n"
        f"────────────────────────"
    )


def run_telegram_polling():
    """Run long-polling loop for local interaction."""
    if not TELEGRAM_BOT_TOKEN:
        print("[Telegram Bot] Error: No TELEGRAM_BOT_TOKEN specified.", file=sys.stderr)
        return

    print(f"[Telegram Bot] Starting long-polling service for @pier_brain_ai_bot...")
    last_update_id = 0

    while True:
        try:
            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates?offset={last_update_id + 1}&timeout=30"
            req = urllib.request.urlopen(url, timeout=35)
            data = json.loads(req.read().decode("utf-8"))

            if data.get("ok"):
                for update in data.get("result", []):
                    last_update_id = update["update_id"]
                    msg = update.get("message")
                    if not msg or "text" not in msg:
                        continue

                    chat_id = msg["chat"]["id"]
                    user_name = msg.get("from", {}).get("first_name", "Pierfrancesco")
                    text = msg["text"]

                    print(f"[Telegram Update] From {user_name} ({chat_id}): {text}")
                    reply_text = process_telegram_message(chat_id, user_name, text)
                    send_telegram_message(chat_id, reply_text, reply_markup=get_main_keyboard())

        except Exception as e:
            print(f"[Telegram Polling Loop] Error: {e}", file=sys.stderr)
            time.sleep(3)


if __name__ == "__main__":
    run_telegram_polling()
